"""added income column

Revision ID: 43fe369979e9
Revises: c7ccfdff49ac
Create Date: 2024-02-18 18:07:57.318565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fe369979e9'
down_revision = 'c7ccfdff49ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
