"""added income column

Revision ID: 5c5b12573492
Revises: 6c1cad50a99e
Create Date: 2024-02-18 18:30:40.759202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5b12573492'
down_revision = '6c1cad50a99e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'players', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###
