"""added income column

Revision ID: 6c1cad50a99e
Revises: 81b6b9389cf7
Create Date: 2024-02-18 18:27:22.872152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1cad50a99e'
down_revision = '81b6b9389cf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
