"""added income column

Revision ID: 81b6b9389cf7
Revises: 43fe369979e9
Create Date: 2024-02-18 18:24:48.770094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b6b9389cf7'
down_revision = '43fe369979e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_name_key', 'players', type_='unique')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('players_name_key', 'players', ['name'])
    # ### end Alembic commands ###
