"""added income column

Revision ID: a988e2e0d7eb
Revises: 5c5b12573492
Create Date: 2024-02-18 18:38:08.384655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a988e2e0d7eb'
down_revision = '5c5b12573492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'name')
    # ### end Alembic commands ###
