"""added income column

Revision ID: ca9d676c9b39
Revises: a988e2e0d7eb
Create Date: 2024-02-19 00:09:19.954537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9d676c9b39'
down_revision = 'a988e2e0d7eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('expense', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expense', 'comment')
    # ### end Alembic commands ###
